/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RAW"
 * 	found in "RAW.asn"
 */

#ifndef	_PlatoonPayload_H_
#define	_PlatoonPayload_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CarID.h"
#include "RawStationID.h"
#include "RawSteeringWheelAngle.h"
#include "RawHeading.h"
#include "RawSpeed.h"
#include "XX.h"
#include "YY.h"
#include "ZZ.h"
#include "constr_SEQUENCE.h"
#ifdef __cplusplus
extern "C" {
#endif

/* PlatoonPayload */
typedef struct PlatoonPayload {
	CarID_t	 carX;
	RawStationID_t	 rawstationID;
	RawSteeringWheelAngle_t	 rawsteeringWheelAngle;
	RawHeading_t	 rawheading;
	RawSpeed_t	 rawspeed;
	XX_t	 xxCoords;
	YY_t	 yyCoords;
	ZZ_t	 zzCoords;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PlatoonPayload_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PlatoonPayload;

#ifdef __cplusplus
}
#endif

#endif	/* _PlatoonPayload_H_ */
#include "asn_internal.h"