/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RAW"
 * 	found in "RAW.asn"
 */

#ifndef	_RAW_H_
#define	_RAW_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RAWHeader.h"
#include "PlatoonPayload.h"
#include "constr_SEQUENCE.h"
#ifdef __cplusplus
extern "C" {
#endif

/* RAW */
typedef struct RAW {
	RAWHeader_t	 header;
	PlatoonPayload_t	 platoon;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RAW_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RAW;

#ifdef __cplusplus
}
#endif

#endif	/* _RAW_H_ */
#include "asn_internal.h"