/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RAW"
 * 	found in "RAW.asn"
 */

#ifndef	_RAWHeader_H_
#define	_RAWHeader_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RawStationID.h"
#include "constr_SEQUENCE.h"
#ifdef __cplusplus
extern "C" {
#endif

/* RAWHeader */
typedef struct RAWHeader {
	RawStationID_t	 rawstationID;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RAWHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RAWHeader;

#ifdef __cplusplus
}
#endif

#endif	/* _RAWHeader_H_ */
#include "asn_internal.h"