/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RAW"
 * 	found in "RAW.asn"
 */

#ifndef	_RawSpeed_H_
#define	_RawSpeed_H_


#include "asn_application.h"

/* Including external dependencies */
#include"NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RawSpeed {
	RawSpeed_standstill	= 0,
	RawSpeed_oneCentimeterPerSec	= 1,
	RawSpeed_unavailable	= 16383
} e_RawSpeed;

/* RawSpeed */
typedef long	 RawSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RawSpeed;
asn_struct_free_f RawSpeed_free;
asn_struct_print_f RawSpeed_print;
asn_constr_check_f RawSpeed_constraint;
ber_type_decoder_f RawSpeed_decode_ber;
der_type_encoder_f RawSpeed_encode_der;
xer_type_decoder_f RawSpeed_decode_xer;
xer_type_encoder_f RawSpeed_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RawSpeed_H_ */
#include "asn_internal.h"