/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RAW"
 * 	found in "RAW.asn"
 */

#ifndef	_RawStationID_H_
#define	_RawStationID_H_


#include "asn_application.h"

/* Including external dependencies */
#include"NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RawStationID */
typedef unsigned long	 RawStationID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RawStationID;
asn_struct_free_f RawStationID_free;
asn_struct_print_f RawStationID_print;
asn_constr_check_f RawStationID_constraint;
ber_type_decoder_f RawStationID_decode_ber;
der_type_encoder_f RawStationID_encode_der;
xer_type_decoder_f RawStationID_decode_xer;
xer_type_encoder_f RawStationID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RawStationID_H_ */
#include "asn_internal.h"