/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RAW"
 * 	found in "RAW.asn"
 */

#ifndef	_YY_H_
#define	_YY_H_


#include "asn_application.h"

/* Including external dependencies */
#include"NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum YY {
	YY_yAxis	= 0,
	YY_oneNegativeMilimeter	= -1,
	YY_onePositiveMilimeter	= 1,
	YY_unavailable	= 2097151
} e_YY;

/* YY */
typedef long	 YY_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_YY;
asn_struct_free_f YY_free;
asn_struct_print_f YY_print;
asn_constr_check_f YY_constraint;
ber_type_decoder_f YY_decode_ber;
der_type_encoder_f YY_encode_der;
xer_type_decoder_f YY_decode_xer;
xer_type_encoder_f YY_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _YY_H_ */
#include "asn_internal.h"