/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RAW"
 * 	found in "RAW.asn"
 */

#ifndef	_ZZ_H_
#define	_ZZ_H_


#include "asn_application.h"

/* Including external dependencies */
#include"NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ZZ {
	ZZ_zAxis	= 0,
	ZZ_oneNegativeMilimeter	= -1,
	ZZ_onePositiveMilimeter	= 1,
	ZZ_unavailable	= 2097151
} e_ZZ;

/* ZZ */
typedef long	 ZZ_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ZZ;
asn_struct_free_f ZZ_free;
asn_struct_print_f ZZ_print;
asn_constr_check_f ZZ_constraint;
ber_type_decoder_f ZZ_decode_ber;
der_type_encoder_f ZZ_encode_der;
xer_type_decoder_f ZZ_decode_xer;
xer_type_encoder_f ZZ_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ZZ_H_ */
#include "asn_internal.h"